version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=slay
      - POSTGRES_USER=MyUser
      - POSTGRES_DB=Movie
volumes:
  postgres_volume: